# tabspaces = 4

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[general]
live_config_reload = true
import = ["/home/uglyboy/.config/alacritty/Nord.toml"]

[cursor.style]
shape = "Beam"

[font]
size = 11

[font.normal]
family = "Maple Mono SC NF"
style = "Regular"

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
