# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty
tabspaces: 4
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

live_config_reload: true

window:
  decorations: none
  dynamic_padding: false
  opacity: 0.9
  padding:
    x: 10
    y: 10

cursor:
  style:
    shape: Beam

scrolling:
  history: 2000
  multiplier: 20
  faux_multiplier: 100
  auto_scroll: true

font:
  size: 11
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular

import:
  # uncomment the flavour you want below:
  - ./Nord.yml
  #- ~/.local/share/dotfiles/config/alacritty/catppuccin-mocha.yml