call plug#begin('~/.vim/plugged')

" install Plug plugins
if filereadable(expand("~/.vimrc.plug"))
  source ~/.vimrc.plug
endif

call plug#end()

" plugin settings
" AirLine
"let g:airline#extensions#tabline#enabled = 1 " 显示窗口tab和buffer
let g:airline#extensions#branch#enabled = 1 " 显示 git branch
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.linenr = ' ☰ '
let g:airline_symbols.maxlinenr = ' '
let g:airline_symbols.colnr = '℅:'
" AirLine Theme Nord
colorscheme nord

" keyboard shortcuts
let mapleader = ','

" Fast saving
nmap <leader>w :w!<cr>
" :W sudo saves the file
" (useful for handling the permission-denied error)
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

map <space> /
map ; :Files<CR>
"nnoremap <leader>b :Buffers<CR>

" Go crazy!
let $LOCALFILE=expand("~/.vimrc.local")
if filereadable($LOCALFILE)
  source $LOCALFILE
endif
