# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty
tabspaces: 4
draw_bold_text_with_bright_colors: true

window:
  decorations: none
  dynamic_padding: false
  opacity: 0.9
  padding:
    x: 10
    y: 10

scrolling:
  history: 2000
  multiplier: 20
  faux_multiplier: 100
  auto_scroll: true

font:
  size: 12
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular
  bold:
    family: "Hack Nerd Font Mono"
    style: Bold
  italic:
    family: "Hack Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font Mono"
    style: Bold Italic
  use_thin_strokes: true

colors:
  primary:
    background: &gruvbox_dark_bg "#2e3440"
    foreground: "#d8dee9"
    dim_foreground: "#a5abb6"
  cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  vi_mode_cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  selection:
    text: CellForeground
    background: "#4c566a"
  search:
    matches:
      foreground: CellBackground
      background: "#88c0d0"
    bar:
      background: "#434c5e"
      foreground: "#d8dee9"
  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#e5e9f0"
  bright:
    black: "#4c566a"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#8fbcbb"
    white: "#eceff4"
  dim:
    black: "#373e4d"
    red: "#94545d"
    green: "#809575"
    yellow: "#b29e75"
    blue: "#68809a"
    magenta: "#8c738c"
    cyan: "#6d96a5"
    white: "#aeb3bb"
