#! /bin/sh
export TERM=linux

pkill picom
pkill dunst
pkill feh

$HOME/.local/bin/redshift.sh
# Launch polybar bars!
$HOME/.local/bin/launch.sh
xsetroot -cursor_name left_ptr &
#xsetroot -cursor_name right_ptr &
xmodmap -e 'pointer = 3 2 1'

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Picom
picom -b

# Dunst
dunst &

# Feh
$HOME/.local/bin/dwall.sh -s lakeside

#Focus in the mouse
#bspc config focus_follows_pointer true

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Border colors
bspc config normal_border_color "#4C566A"
bspc config active_border_color "#434C5E"
bspc config focused_border_color "#2E3440"
bspc config presel_feedback_color "#3B4252"

bspc rule -a Microsoft-edge desktop='^1' follow=on
bspc rule -a obsidian desktop='^2' follow=on
bspc rule -a Typora desktop='^2' follow=on
bspc rule -a bluemail desktop='^2' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a netease-cloud-music state=tiled desktop='^4' follow=on
bspc rule -a TDAppDesktop desktop='^5' follow=on
bspc rule -a Code desktop='^5' follow=on
bspc rule -a rofi state=floating sticky=on
bspc rule -a feh state=floating

#bspc rule -a Alacritty state=floating rectangle=1280x720+640+320
bspc rule -a Alacritty state=floating rectangle=1960x1080+300+140