#! /bin/bash
export TERM=linux

pgrep -x sxhkd > /dev/null || sxhkd &

# 灵感来源于 gk
_c() { bspc config "$@"; }
_m() { bspc monitor "$@"; }
_r() { bspc rule -a "$@"; }
_s() {
	pkill -x "$1"
	{
		sleep 0.1
		"$@" &
	}
}

_m -d I II III IV V VI

_c border_width         0
_c window_gap           10
_c split_ratio          0.52
_c borderless_monocle   true
_c gapless_monocle      true

_c pointer_modifier mod1
_c pointer_action1 resize_side
_c pointer_action1 resize_corner
_c pointer_action3 move

# 边框颜色
_c normal_border_color "#4C566A"
_c active_border_color "#434C5E"
_c focused_border_color "#2E3440"
_c presel_feedback_color "#3B4252"

# 启动服务
# 并行启动常规服务
(
    _s picom -b
    _s redshift
    _s dunst
    _s xsetroot -cursor_name left_ptr
    _s polybar --reload main
) &

# 动态壁纸
#_s ~/.fehbg
~/.local/bin/dwall.sh -s lakeside &
# 权限管理
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Window rules ----------------------------------------------#
#remove all rules first
bspc rule -r *:*

## web
declare -a web=(Microsoft-edge)
for i in ${web[@]}; do
	bspc rule -a $i desktop='^1' follow=on focus=on
done

## office
declare -a office=(obsidian Typora Zotero)
for i in ${office[@]}; do
	_r $i desktop='^2' follow=on
done

## files
declare -a files=(lf)
for i in ${files[@]}; do
	bspc rule -a $i desktop='^3' follow=on focus=on
done

## media
declare -a media=(melonDS GStreamer Io.github.celluloid_player.Celluloid mpv)
for i in ${media[@]}; do
	_r $i desktop='^4' follow=on
done

## chat
declare -a chat=(wechat Bytedance-feishu TDAppDesktop)
for i in ${chat[@]}; do
	_r $i desktop='^5' follow=on focus=on
done

## code
declare -a code=(Code)
for i in ${code[@]}; do
	_r $i desktop='^6' follow=on
done

## floating
declare -a terminal=(Alacritty kitty)
for i in ${terminal[@]}; do
	_r $i state=floating rectangle=1280x720+640+100 focus=on
done

declare -a floating=(rofi feh Zathura)
for i in ${floating[@]}; do
	_r $i state=floating follow=on focus=on
done

_r '*:*:画中画' follow=false state=floating sticky=on
_r 'Microsoft-edge:*:Bitwarden' state=floating
