#! /bin/sh

pkill picom
pkill dunst
pkill feh

$HOME/.local/bin/redshift.sh
# Launch polybar bars!
$HOME/.local/bin/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Feh
feh --bg-fill $HOME/.config/wallpaper.jpg

#Picom
picom -b

#Focus in the mouse
#bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Border colors
bspc config normal_border_color "#4C566A"
#bspc config active_border_color "#010011"
bspc config focused_border_color "#2E3440"
bspc config presel_feedback_color "#3341CF"

bspc rule -a feh state=floating
bspc rule -a Microsoft-edge desktop='^1' follow=on
bspc rule -a obsidian desktop='^2' follow=on
bspc rule -a Io.github.celluloid_player.Celluloid desktop='^5' follow=on
bspc rule -a rofi state=floating sticky=on
