[general]
accounts = Exmail,Aliyun
metadata = ~/.local/share/offlineimap
pythonfile = ~/.local/share/dotfiles/desktop/mutt/get_pass.py

[Account Aliyun]
localrepository = Local-Aliyun
remoterepository = Remote-Aliyun

[Account Exmail]
localrepository = Local-Exmail
remoterepository = Remote-Exmail

[Repository Local-Aliyun]
type = Maildir
localfolders = ~/.local/share/Mail/Aliyun
sync_deletes = False

[Repository Local-Exmail]
type = Maildir
localfolders = ~/.local/share/Mail/Exmail
sync_deletes = False

[Repository Remote-Aliyun]
type = IMAP
sync_deletes = False
remotehost = imap.aliyun.com
remoteuser = uglyboy@aliyun.com
remotepasseval = get_pass("uglyboy@aliyun.com")
auth_mechanisms = LOGIN
folderfilter = lambda foldername: foldername in ["INBOX", "Archive", "&jSJSoU,hYG8-", "&lj+RzE6R-", '&XfJT0ZAB-', "&V4NXPpCuTvY-"]
nametrans = lambda foldername: re.sub ('&jSJSoU,hYG8-', '财务',
                               re.sub ('&lj\+RzE6R-', 'Notify',
                               re.sub ('&XfJT0ZAB-', 'Sent',
                               re.sub ('&V4NXPpCuTvY-', 'Junk', foldername))))
createfolder = true
ssl = yes
sslcacertfile = OS-DEFAULT

[Repository Remote-Exmail]
type = IMAP
sync_deletes = False
remotehost = imap.exmail.qq.com
remoteuser = uglyboy@uglyboy.cn
remotepasseval = get_pass("uglyboy@uglyboy.cn")
auth_mechanisms = LOGIN
folderfilter = lambda foldername: foldername in ["INBOX", "Archive", "Junk", "Sent Messages"]
nametrans = lambda foldername: re.sub ('Sent\ Messages', 'Sent', foldername)
createfolder = true
ssl = yes
sslcacertfile = OS-DEFAULT
