#:schema https://yazi-rs.github.io/schemas/yazi.json

[plugin]
prepend_fetchers = [
    { id = "git-status", url = "?*", run = "git", group = "git" },
]

[mgr]
sort_by = "natural"
linemode = "size"

[preview]
max_width = 1200