"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_by = "natural"
linemode = "size"

[preview]
max_width = 1200

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"